GestionMusiques/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^musiques/', include('musiques.urls')),
]

musiques/urls.py
from django.conf.urls import url
from .views import home, MorceauDetailView, MorceauList, MorceauAjoutView, UpdateMorceauView, MorceauDeleteView, ArtisteDetailView, ArtisteList, ArtisteAjoutView, UpdateArtisteView, ArtisteDeleteView


app_name = 'musiques'
urlpatterns = [
    url(r'^home/$', home, name='home'),
    url(r'^(?P<pk>\d+)$', MorceauDetailView.as_view(), name='morceau_detail'),
    url(r'^$', MorceauList.as_view(), name='morceau_list'),
    url(r'^Ajout_morceau/', MorceauAjoutView.as_view(), name='morceau_ajout'),
    url(r'^Update_morceau/(?P<pk>\d+)$',
        UpdateMorceauView.as_view(), name='morceau_update'),
    url(r'^Delete_morceau/(?P<pk>\d+)$',
    MorceauDeleteView.as_view(), name='morceau_delete'),
    url(r'^artiste/(?P<pk>\d+)$', ArtisteDetailView.as_view(), name='artiste_detail'),
    url(r'^artiste', ArtisteList.as_view(), name='artiste_list'),
    url(r'^Ajout_artiste/', ArtisteAjoutView.as_view(), name='artiste_ajout'),
    url(r'^Update_artiste/(?P<pk>\d+)$',
        UpdateArtisteView.as_view(), name='artiste_update'),
    url(r'^Delete_artiste/(?P<pk>\d+)$',
        ArtisteDeleteView.as_view(), name='artiste_delete'),
]

musiques/models.py
from django.db import models
from django.urls import reverse

class Morceau(models.Model):
    artiste = models.ForeignKey('Artiste',null=False,on_delete=models.CASCADE)
    titre = models.CharField(max_length=64)
    date_sortie = models.DateField(null=True)
    album = models.CharField(null=True,max_length=64)
    genre = models.CharField(null=True,max_length=64)
    parole =models.CharField(null=True,max_length=2000)


    def __str__(self):
        return '{self.titre} ({self.artiste.nom})'.format(self=self)

    def get_absolute_url(self):
        return reverse('musiques:morceau_detail', args=[str(self.id)])

class Artiste(models.Model):
    nom = models.CharField(max_length=64)
    prenom = models.CharField(null=True,max_length=64)
    date_naiss = models.DateField(null=True)

    def __str__(self):
        return '{self.nom} {self.prenom}'.format(self=self)

    def get_absolute_url(self):
        return reverse('musiques:artiste_detail', args=[str(self.id)])

musiques/views.py
from django.shortcuts import render

from django.http import HttpResponse


def home(request):
    return HttpResponse("Hello, world. You're at the polls index.")
# def morceau_detail(request,pk):
#     return HttpResponse("morceau_detail")


from django.views.generic.list import ListView
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView
from .models import Morceau, Artiste
from django.urls import reverse_lazy


class MorceauDetailView(DetailView):
    model = Morceau
    context_object_name = "Morceau"


class MorceauList(ListView):
    model = Morceau
    context_object_name = 'Morceau'


class UpdateMorceauView(UpdateView):
    model = Morceau
    fields = ['titre', 'artiste','album', 'date_sortie','genre','parole']


class MorceauAjoutView(CreateView):
    model = Morceau
    fields = ['titre', 'artiste','album', 'date_sortie','genre','parole']


class MorceauDeleteView(DeleteView):
    model = Morceau
    success_url = reverse_lazy('musiques:morceau_list')

class ArtisteDetailView(DetailView):
    model = Artiste
    context_object_name = "Artiste"


class ArtisteList(ListView):
    model = Artiste
    context_object_name = 'Artiste'


class UpdateArtisteView(UpdateView):
    model = Artiste
    fields = ['nom', 'prenom', 'date_naiss']


class ArtisteAjoutView(CreateView):
    model = Artiste
    fields = ['nom', 'prenom', 'date_naiss']


class ArtisteDeleteView(DeleteView):
    model = Artiste
    success_url = reverse_lazy('musiques:artiste_list')

musiques/templates/musiques/artiste_confirm_delete.html
{% extends "musiques/baseMusique.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Etes-vous sure de bien vouloir supprimer cette musique : "{{ object }}"?</p>
    <input type="submit" class="btn btn-success" value="Confirmer" />
</form>

{% endblock content %}

musiques/templates/musiques/artiste_detail.html
{% extends "musiques/baseMusique.html" %}
{% block content %}
<section class='detail'>
  <section id='tableau'>
    <table class="table">
      <tr>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Date de naissance</th>
        <th>Discographie</th>
        <th></th>
      </tr>
      <tr>
          <td>{{ object.nom }}</td>
          <td>{{ object.prenom }}</td>
          <td>{{ object.date_naiss }}</td>
          <td>
            <ul>
              {% for morceau in object.morceau_set.all %}
              <li>{{morceau.titre}} {{morceau.date_sortie}}</li>
              {% endfor %}
            </ul>
          </td>
      </tr>
      </table >
    </section>
    <section class='buttons'>
        <a href="{% url 'musiques:artiste_update' object.id %}"><button class="btn btn-warning">Modifier</button></a>
        <a href="{% url 'musiques:artiste_delete' object.id %}"><button class="btn btn-danger">Supprimer</button></a>
        <a href="{% url 'musiques:artiste_list' %}"><button class="btn btn-primary">Liste des artistes</button></a>
      </section>

    </section>
{% endblock content %}

musiques/templates/musiques/artiste_form.html
{% extends "musiques/baseMusique.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="Sauvegarder" />
</form>
{% endblock content %}

musiques/templates/musiques/artiste_list.html
{% extends "musiques/baseMusique.html" %}
{% block content %}
<div id="table" class="table-editable">
    <a href="{% url 'musiques:artiste_ajout'%}"><span class="table-add glyphicon glyphicon-plus" ></span></a>
    <table class="table">
      <tr>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Date de naissance</th>
        <th></th>
      </tr>
      {% for a  in Artiste  %}
      <tr>
          <td><a href="{% url 'musiques:artiste_detail' a.id %}" >{{ a.nom }}</a></td>
          <td>{{ a.prenom }}</td>
          <td>{{ a.date_naiss }}</td>
          <td><a href="{% url 'musiques:artiste_delete' a.id %}" id='{{a.nom}}-delete'><span class="table-remove glyphicon glyphicon-remove"></a></td>
      </tr>
        {% empty %}
          <td>Pas de morceau</td>
        {% endfor %}

    </table>
  </div>

  <!-- <button id="export-btn" class="btn btn-primary">Export Data</button>
  <p id="export"></p>
</div>
    {% for m  in Morceau  %}
        <li><a href="{% url 'musiques:morceau_detail' m.id %}">{{ m }}</a></li>
    {% empty %}
        <li>Pas de morceau</li>

    {% endfor %} -->
{% endblock content %}

musiques/templates/musiques/artiste_update_form.html
{% extends "musiques/baseMusique.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock content %}

musiques/templates/musiques/baseMusique.html
<!DOCTYPE html>
<html lang="fr">
<head>
    {% load static%}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'musiques/style.css' %}">
    <title>{% block title %}   Musiques {% endblock title %}</title>
</head>
<body>
  <header>
    <h1>Gestion de musiques</h1>
    <nav>
      <ul>
        <li><a href="{% url 'musiques:morceau_list' %}">Morceau</a></li>
        <li><a href="{% url 'musiques:artiste_list' %}">Artiste</a></li>
      </ul>
    </nav>
  </header>
    {% block header  %}    {% endblock header  %}
    {% block content %}    {% endblock content %}
    {% block footer  %}    {% endblock footer  %}

</body>
</html>

musiques/templates/musiques/form_create.html
{% extends "musiques/baseMusique.html" %}
{% block content %}

    {% for m  in Morceau  %}
        <li><a href="./update/{{ m.id }}">{{ m }}</a></li>
    {% empty %}
        <li>Pas de morceau</li>

    {% endfor %}
{% endblock content %}

musiques/templates/musiques/morceau_confirm_delete.html
{% extends "musiques/baseMusique.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Etes-vous sure de bien vouloir supprimer cette musique : "{{ object }}"?</p>
    <input class="btn btn-success"type="submit" value="Confirmer" />
</form>

{% endblock content %}

musiques/templates/musiques/morceau_detail.html
{% extends "musiques/baseMusique.html" %}
{% block content %}
<section class='detail'>
  <section id="cadre">
    <ul>
      <li><strong>TITRE :</strong> {{object.titre}}</li>
      <li><strong>ARTISTE :</strong> {{object.artiste}}</li>
      <li><strong>ALBUM :</strong> {{object.album}}</li>
      <li><strong>DATE DE SORTIE :</strong> {{object.date_sortie}}</li>
      <li><strong>GENRE :</strong> {{object.genre}}</li>
    </ul>
  </section>
  <br/>
  <section>
    <h3>Parole</h3>
    <p>{{object.parole}}</p>
  </section>
  <section class='buttons'>
    <a href="{% url 'musiques:morceau_update' object.id %}" id='{{object.titre}}-update'><button class="btn btn-warning">Modifier</button></a>
    <a href="{% url 'musiques:morceau_delete' object.id %}" id='{{object.titre}}-delete'><button class="btn btn-danger">Supprimer</button></a>
    <a href="{% url 'musiques:morceau_list' %}"><button class="btn btn-primary">Liste des musiques</button></a>

  </section>

</section>


{% endblock content %}

musiques/templates/musiques/morceau_form.html
{% extends "musiques/baseMusique.html" %}
{% block content %}
<h2 class='titre'>Création d'un morceau</h2>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="Sauvegarder" />
</form>
{% endblock content %}

musiques/templates/musiques/morceau_list.html
{% extends "musiques/baseMusique.html" %}
{% block content %}
<div id="table" class="table-editable">
    <a href="{% url 'musiques:morceau_ajout'%}"><span class="table-add glyphicon glyphicon-plus" ></span></a>
    <table class="table">
      <tr>
        <th>Titre</th>
        <th>Artiste</th>
        <th>Date de sortie</th>
        <th></th>
      </tr>
      {% for m  in Morceau  %}
      <tr>
          <td><a href="{% url 'musiques:morceau_detail' m.id %}" id='{{m.titre}}'>{{ m.titre }}</a></td>
          <td><a href="{% url 'musiques:artiste_detail' m.artiste.id %}">{{ m.artiste }}</a></td>
          <td>{{ m.date_sortie }}</td>
          <td><a href="{% url 'musiques:morceau_delete' m.id %}" id='{{m.titre}}-delete'><span class="table-remove glyphicon glyphicon-remove"></a></td>
      </tr>
        {% empty %}
          <td>Pas de morceau</td>
        {% endfor %}

    </table>
  </div>

  <!-- <button id="export-btn" class="btn btn-primary">Export Data</button>
  <p id="export"></p>
</div>
    {% for m  in Morceau  %}
        <li><a href="{% url 'musiques:morceau_detail' m.id %}">{{ m }}</a></li>
    {% empty %}
        <li>Pas de morceau</li>

    {% endfor %} -->
{% endblock content %}

musiques/templates/musiques/morceau_update_form.html
{% extends "musiques/baseMusique.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock content %}